// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Connection struct {
	Uuid        string
	MachineUuid string
	CreatedAt   pgtype.Timestamptz
	LastUpdated pgtype.Timestamptz
}

type Machine struct {
	Uuid        string
	MachineType string
	CreatedAt   pgtype.Timestamp
	LastUpdated pgtype.Timestamp
}

type MachineTypeLeader struct {
	MachineUuid string
}

type Room struct {
	Uuid            string
	MachineUuid     string
	Name            string
	Script          string
	DestroyOnOrphan bool
	CreatedAt       pgtype.Timestamp
	LastUpdated     pgtype.Timestamp
}

type RoomDatum struct {
	RoomUuid pgtype.Text
	Key      string
	Value    pgtype.Text
}

type RoomMembership struct {
	ConnectionUuid string
	RoomUuid       string
}
